/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.2/userguide/building_java_projects.html
 */

// Define variables for project configurations
val projectGroup = "dev.onelenyk"
val projectVersion = "1.0.0"
val mainAppClassName = "$projectGroup.pdfproject.AppKt"



plugins {
    id("org.jetbrains.kotlin.jvm") version "1.8.22"
    id("com.github.johnrengelman.shadow") version "7.0.0" // Shadow plugin for creating a fat JAR
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

group = projectGroup
version = projectVersion

repositories {
    mavenCentral()
    maven(url = "https://jitpack.io")
}

dependencies {

    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:30.1.1-jre")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    //cli library
    implementation("info.picocli:picocli:4.6.2")

    implementation("dev.onelenyk:gitignore-parser:v0.1.6")

    implementation("com.itextpdf:itext7-core:7.1.16")
    implementation("com.itextpdf:html2pdf:3.0.3")
}


application {
    // Define the main class for the application.
    mainClass.set(mainAppClassName)
}

tasks.shadowJar {
    archiveClassifier.set("")
    manifest {
        attributes["Main-Class"] = mainAppClassName
    }
}

tasks.withType<Jar> {
    manifest {
        attributes["Main-Class"] = mainAppClassName
    }
    archiveFileName.set("pdfproject.jar")
}